services:
  user_service:
    build: 
      context: ./user_service
    container_name: user_service
    ports:
      - "5001:5001"

  restaurant_service:
    build:
      context: ./restaurant_service
    container_name: restaurant_service
    ports:
      - "5002:5002"

  order_service:
    build: 
      context: ./order_service
    container_name: order_service
    ports:
      - "5003:5003"

  payment_service:
    build:
      context: ./payment_service
    container_name: payment_service
    ports:
      - "5004:5004"

  delivery_service:
    build:
      context: ./delivery_service
    container_name: delivery_service
    ports:
      - "5005:5005"

  notification_service:
    build:
      context: ./notification_service
    container_name: notification_service
    ports:
      - "5006:5006"
  fluent_bit:
    image: fluent/fluent-bit:latest
    container_name: fluent_bit
    platform: linux
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "2020:2020"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Optional: disable security if you want a quick setup
    ports:
      - "9200:9200"
    networks:
      - elasticnet

networks:
  elasticnet:
    driver: bridge
