services:
  # Microservices
  user_service:
    build: 
      context: ./user_service
    container_name: user_service
    ports:
      - "5001:5001"
    environment:
      - ENVIRONMENT=cloud
    volumes:
      - ./logs:/app/logs

  restaurant_service:
    build:
      context: ./restaurant_service
    container_name: restaurant_service
    ports:
      - "5002:5002"
    environment:
      - ENVIRONMENT=on-prem
    volumes:
      - ./logs:/app/logs

  order_service:
    build: 
      context: ./order_service
    container_name: order_service
    ports:
      - "5003:5003"
    environment:
      - ENVIRONMENT=cloud
    volumes:
      - ./logs:/app/logs

  payment_service:
    build:
      context: ./payment_service
    container_name: payment_service
    ports:
      - "5004:5004"
    environment:
      - ENVIRONMENT=multi-cloud
    volumes:
      - ./logs:/app/logs

  delivery_service:
    build:
      context: ./delivery_service
    container_name: delivery_service
    ports:
      - "5005:5005"
    environment:
      - ENVIRONMENT=cloud
    volumes:
      - ./logs:/app/logs

  notification_service:
    build:
      context: ./notification_service
    container_name: notification_service
    ports:
      - "5006:5006"
    environment:
      - ENVIRONMENT=on-prem
    volumes:
      - ./logs:/app/logs

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elknet

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elknet

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/app/logs
    depends_on:
      - elasticsearch
    networks:
      - elknet
networks:
  elknet:
    driver: bridge
